---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - werf.io
  resources:
  - werfbundles
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - werf.io
  resources:
  - werfbundles/status
  verbs:
  - get
  - patch
  - update
